# Generated by Django 3.2.7 on 2021-12-05 21:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ST_System', '0003_alter_ticket_statuses_ticket_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_statuses',
            name='ticket_status_color',
            field=colorfield.fields.ColorField(choices=[('#000000', 'black'), ('#FF0000', 'red'), ('#0000FF', 'blue'), ('#008000', 'green'), ('#FFFF00', 'yellow'), ('#FFA500', 'orange'), ('#800080', 'purple')], default='black', max_length=18),
        ),
    ]
