# Generated by Django 3.2.7 on 2021-12-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST_System', '0005_auto_20211206_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorities',
            name='priority_name',
        ),
        migrations.AddField(
            model_name='priorities',
            name='priority_level',
            field=models.IntegerField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'Higj')], default=1),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.IntegerField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=1),
        ),
    ]
