# Generated by Django 3.2.7 on 2021-12-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST_System', '0006_auto_20211213_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
