# Generated by Django 3.2.7 on 2021-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
